export enum NavModeSwitcherEvent {
	/**
	 * Changed events
	 */
	AP_CHANGED,
	NAVIGATION_MODE_CHANGED,
	TOGA_CHANGED,
	HEADING_LOCKED_CHANGED,
	ALTITUDE_LOCKED_CHANGED,
	SIMULATOR_ALTITUDE_LOCKED_CHANGED,
	ALTITUDE_SLOT_CHANGED,
	SELECTED_ALTITUDE_1_CHANGED,
	SELECTED_ALTITUDE_2_CHANGED,
	SELECTED_ALTITUDE_3_CHANGED,
	GROUNDED_CHANGED,


	/**
	 * Press events
	 */
	HDG_HOLD_PRESSED,
	HDG_SEL_PRESSED,

	SPD_PRESSED,
	SPD_INTERVENTION_PRESSED,
	FLC_PRESSED,
	APPR_PRESSED,
	VS_PRESSED,
	VNAV_PRESSED,
	LNAV_PRESSED,
	ALT_HOLD_PRESSED,
	ALT_INTERVENTION_PRESSED,
}