export enum HDSpeedType {
	'SPEED_TYPE_ECON',
	'SPEED_TYPE_SELECTED',
	'SPEED_TYPE_RESTRICTION',
	'SPEED_TYPE_TRANSITION',
	'SPEED_TYPE_ACCELERATION',
	'SPEED_TYPE_PROTECTED',
	'SPEED_TYPE_WAYPOINT'
}